odahu/odahu-flow

- .travis.yml
- packages/operator/Gopkg.lock
- packages/operator/Makefile
- packages/operator/README.MD
- packages/operator/cmd/api/main.go
- packages/operator/docs/docs.go
- packages/operator/docs/swagger.json
- packages/operator/docs/swagger.yaml
- packages/operator/pkg/config/api/api.go
- packages/operator/pkg/utils/manager.go
- packages/operator/pkg/webserver/routes/prometheus_test.go
- packages/operator/pkg/webserver/server.go
Provided new config options to startup the API server that
will use kubebuilder test assets to emulate the kube API.
Upgraded the swag to the 1.6.5 version.
Allowed to configure the name of sed executable in the Makefile.
Removed the redundant operator dependencies.
Implemented graceful shutdown for API service.
Optionally run the linux specific tests.
> [feat] Startup the API server without a kubernetes cluster

- packages/operator/docs/docs.go
- packages/operator/docs/swagger.json
- packages/operator/docs/swagger.yaml
- packages/operator/pkg/config/config.go
- packages/operator/pkg/config/user.go
- packages/operator/pkg/trainer/git.go
- packages/operator/pkg/utils/ssh.go
- packages/operator/pkg/webserver/routes/v1/collector.go
- packages/operator/pkg/webserver/routes/v1/user/userinfo.go
* Rename "user" field to "users" because popular unix environment variable "USER" overrides the configuration.
> [feat] Added sign out url config variable

- packages/tests/stuff/training_stuff.sh
Hotfix to substitute default `airflow.dag_*` variables values if there are no defined in cluster profile.
> [fix] for training_stuff

- .travis.yml
- Makefile
- codecov.yaml
- fixed that code coverage updated with failed build (as not all code coverage counted).
- added missed lines in code coverage report for python
- raised the bottom line of range for code coverage as it shows the line coverage
> Test report python

- packages/cli/odahuflow/cli/__main__.py
- packages/cli/odahuflow/cli/main.py
- packages/cli/odahuflow/cli/parsers/security.py
- packages/cli/tests/parsers/test_security.py
- packages/sdk/odahuflow/sdk/clients/api.py
In the initial issue #257 @BPylypenko wrote that expected behavior is displaying help for command like this: `login --url --help`. From where I stand, taking `--help` as a URL is natural, it is expected behavior of `click` library. Everything that follows a non-flag option (that expects a value) is considered the value. Instead of hacking this behavior it was decided to validate URL after discussion with @vlad-tokarev.
**Change notes:** 
- I changed `RemoteAPIClient:info()` to wrap exceptions from `requests` library into `APIConnectionException` and raise up. 
- I wrote a simple unit test that simulates calling `login --url --help` from #257. But as far as I understand currently we don't have any other unit tests for login section. **Should I create a task to add them?**
- I added a minor …
> Fix #257 - Validate API host URL on login in CLI

- packages/operator/pkg/apis/connection/connection.go
- packages/operator/pkg/repository/connection/http/connection.go
- packages/operator/pkg/repository/connection/kubernetes/connection.go
- packages/operator/pkg/repository/connection/kubernetes/connection_test.go
- packages/operator/pkg/repository/connection/repository.go
- packages/operator/pkg/repository/connection/vault/connection.go
- packages/operator/pkg/repository/connection/vault/connection_test.go
- packages/operator/pkg/webserver/routes/v1/connection/connection_routes.go
- packages/operator/pkg/webserver/routes/v1/connection/connection_routes_test.go
- packages/operator/pkg/webserver/routes/v1/packaging/model_packaging_test.go
- packages/operator/pkg/webserver/routes/v1/packaging/model_packaging_validation_test.go
- packages/operator/pkg/webserver/routes/v1/training/model_training_test.go
- packages/operator/pkg/webserver/routes/v1/training/model_training_validation_test.go
Fix #202. Original issue: when creating a connection, secrets are not masked in response connection object.
@vlad-tokarev since you're well-familiar with the project structure, I would appreciate your advice here regarding the following: I masked secrets on controller-level. It is super-easy one-line fix, **but** it is not completely consistent with the rest of code. In case of retrieving a connection with masked secrets masking takes place on repository-level. The repository has 2 methods: `GetConnection` and `GetDecryptedConnection`. So this masking logic (what to mask, what not to mask) gets spread a bit. 
Maybe I should refactor repository's `CreateConnection` so that it would return newly created masked **connection** and **error** instead of just error as it is now? Then masking …
> Fix #202: mask secrets in connection creation response

- Makefile
- packages/cli/tests/parsers/test_local.py
- packages/sdk/odahuflow/sdk/local/training.py
- packages/sdk/tests/local/__init__.py
- packages/sdk/tests/local/test_local_training.py
Fixes #193. Original issue is that `local training` does not consider `artifactNameTemplate` from training configuration. Instead it saves the output model files into `--output-dir` if it is provided. Otherwise it defaults to `$HOME/.odahuflow/<name>-<version>-datetime/ directory.
I suggest to change the behavior to the following:
- result model's files are saved to the directory which is named according to the `artifactNameTemplate`. If the template is not provided it defaults to `'{{ .Name }}-{{ .Version }}-{{ .RandomUUID }}'`;
- this directory will be saved under the path provided via `--output-dir` or in `config.LOCAL_MODEL_OUTPUT_DIR` by default.
You can check tests out to see it in action.
By example:
before: /path/to/output_dir/ contains model files
after: …
> [#193] Fixed local training to consider artifactNameTemplate

- packages/tests/stuff/training_stuff.sh
`training_stuff.sh` script must decode keySecret from base64 before passwing it to rclone.
Because of that Azure tests failed. They passed well with this change.
https://jenkins.cicd.odahu.org/view/OdahuFlow%20Deploy/job/Azure_Create_cluster/525/robot/
> Decode base64 keySecret received from API in testing script

- packages/sdk/odahuflow/sdk/clients/api.py
Previous custom implementation did not handle ReadTimeout and other cases properly (only ConnectionTimeout was handled)
> #fix retry policy for SDK

- packages/cli/odahuflow/cli/parsers/security.py
- packages/sdk/odahuflow/sdk/clients/api.py
- packages/sdk/odahuflow/sdk/clients/oauth_handler.py
- packages/sdk/odahuflow/sdk/clients/oidc.py
- packages/sdk/odahuflow/sdk/config.py
- added `MODEL_HOST` config variable to reset during logout `def _reset_credentials()`;
- added `_issuer_url` param, so that you could logon through RemoteAPIClient passing client_id, client_secret, and issuer and not  setting issuer through `config.ISSUER_URL`
> added issuer_url parameter in RemoteAPIClient 

- packages/operator/controllers/modeldeployment_controller_test.go
- packages/operator/controllers/modelpackaging_controller_test.go
- packages/operator/controllers/modeltraining_controller_test.go
Refactored tests:
- Each test gets a resource with randomly generated Name. That helps avoid collisions when running tests in parallel.
- On resource creation we now wait until the object becomes actually available in K8s (until now object was considered created if reconcilation was triggered twice, which is not completely reliable)
- Renamed some tests because Go tooling mixes them up...
> CRD controllers tests refactoring

- packages/operator/api/v1alpha1/modeldeployment_types.go
- packages/operator/controllers/modeldeployment_controller.go
- packages/operator/controllers/modeldeployment_controller_test.go
- packages/operator/controllers/modelpackaging_controller_test.go
- packages/operator/controllers/modeltraining_controller_test.go
- packages/operator/docs/docs.go
- packages/operator/docs/swagger.json
- packages/operator/docs/swagger.yaml
- packages/operator/go.mod
- packages/operator/pkg/apiserver/routes/v1/deployment/model_deployment_validation.go
- packages/operator/pkg/apiserver/routes/v1/deployment/model_deployment_validation_test.go
- packages/operator/pkg/config/deployment.go
- packages/sdk/odahuflow/sdk/models/model_deployment_config.py
- packages/sdk/odahuflow/sdk/models/model_deployment_spec.py
Change notes:
- upgraded Knative 0.15.0 -> 0.17.0 (see https://github.com/odahu/odahu-infra/pull/24). It is required to control Pod's tolerations/nodeSelector/affinity
- upgraded Knative API library. It caused conflicts in transient dependencies that I managed to eliminate via `replace` directive of `go.mod` (it is pure luck it worked!)
- Deployment configuration now has `nodePools` field. The format is the same as for training/packaging:
```
"nodePools": [
{
"nodeSelector": {
"label": "value"
},
"tags": ["tag1", "tag2"]
}
],
```
- Deployment spec now has the new field `nodeSelector` which must exactly match a selector from config. Otherwise API returns 400 with a validation error.
Relative PRs:
https://github.com/odahu/odahu-infra/pull/24 …
> [#243] Choose node pools for deployments

- packages/operator/pkg/apiserver/routes/v1/deployment/model_deployment_validation.go
- packages/operator/pkg/apiserver/routes/v1/deployment/model_deployment_validation_test.go
- packages/operator/pkg/apiserver/routes/v1/training/model_training_validation.go
- packages/operator/pkg/apiserver/routes/v1/training/model_training_validation_test.go
- packages/operator/pkg/validation/validation.go
Fixes #348.
We use some fields as label values. We have to make sure that they are in the format that K8s expects. Otherwise a resource creation fails.
> [#348] Validate fields that used as K8s labels

- packages/operator/pkg/rclone/azureblob.go
Possible options:
- full uri like `https://storage-account-name.windows.net/blob-container-name/path/to/file`
- path like `/blob-container-name/path/to/file`
- path without leading slash like `blob-container-name/path/to/file`
Before only the last option worked.
Fixes #345.
> [#345] Handle all kinds of URI for azure blob connections

- packages/cli/odahuflow/cli/parsers/local/packaging.py
- packages/cli/odahuflow/cli/parsers/local/training.py
Closes #158 
From issue comments:
> We found out that the behavior it expected: parse files passed as CLI arguments. If ModelTraining or ToolchainIntegration are not found there, it tries to pull them from API. It user is not logged it, well, it is expected that we cannot proceed until they fix it. 
> 
> Also, currently if training/toolchain are fetched from API server, an appropriate message shows up in --verbose mode only. After discussion with @BPylypenko (reporter) we decided that CLI should print the message anyway, with or without verbose.
> [#158] Minor cli messages

- .travis.yml
This tells Travis to build on Push/PR to all branches matching regex `^release\/.*$`.
> Added regex for release branches to the list for Travis

- .travis.yml
- packages/cli/odahuflow/cli/parsers/config.py
- packages/operator/pkg/rclone/azureblob.go
Fix #307 
Mask `ODAHUFLOWCTL_OAUTH_CLIENT_SECRET` (and other properties ending with `_SECRET` as well) in output of `odahuflowctl config all`.
Before:
```
ODAHUFLOWCTL_OAUTH_CLIENT_SECRET - Set OAuth2 Client id
default: ''
current: 'abc'
```
After:
```
ODAHUFLOWCTL_OAUTH_CLIENT_SECRET - Set OAuth2 Client id
default: ''
current: '****'
```
> [#307] Mask client secret in CLI config

- packages/cli/odahuflow/cli/parsers/gppi.py
Fixes #375 
Before:
```
Commands:
predict  :param ctx: :param input_file: Input JSON file for predictions :param output_dir:...
test     Initialize GPPI model and try to execute api Next API are tested: Executes .info()...
```
After:
```
Commands:
predict  Invokes a prediction on a trained model.
test     Initialize GPPI model and try to execute api.
```
> [#375] Minor fix in CLI gppi group documentation

- packages/cli/odahuflow/cli/main.py
added -h flag, so if you indicate -h, you will get a help window.
> help option names (-h, --help)

- packages/cli/odahuflow/cli/parsers/completion.py
before:
```
Error: 'cmd'
For more information rerun command with --verbose flag
```
after
`Error: "cmd" shell is not supported.`
> fix for not supported shells, completion will give human friendly error
