packages/cli/odahuflow/cli/parsers/gppi.py, packages/sdk/odahuflow/sdk/gppi/entrypoint_invoke.py, packages/sdk/odahuflow/sdk/gppi/executor.py
#88 
We need this feature for cli-packager, but I also find it useful for personal use by anyone who wants to get predictions from GPPI
=> [#88] Ability to make predictions with odahuflowctl and GPPI archive

packages/cli/Pipfile.lock, packages/robot/Pipfile.lock, packages/sdk/Pipfile, packages/sdk/Pipfile.lock
Jenkins build job started failing because of not hash matching
between Pipfile.lock and PyPi.
=> [fix] Updated the python dependencies

packages/operator/Makefile, packages/operator/hack/tests/thirdparty_crds/taskruns.tekton.dev.yaml, packages/operator/hack/tests/thirdparty_crds/tasks.tekton.dev.yaml, packages/operator/pkg/config/training/training.go, packages/operator/pkg/controller/modeltraining/modeltraining_controller.go, packages/operator/pkg/controller/modeltraining/modeltraining_controller_test.go, packages/operator/pkg/controller/modeltraining/tekton.go, packages/operator/pkg/repository/util/kubernetes/utils.go, packages/operator/pkg/repository/util/kubernetes/utils_test.go
* Fixed the ConvertOdahuflowResourcesToK8s function and added
tests for it.
* If a model training contains GPU resources then the training pod
will be deploy on a GPU node pool.
* Added tests for the model training controller.
=> [#28] GPU support

containers/operator/Dockerfile, packages/operator/pkg/utils/zip.go, scripts/Jenkinsfile
* Jenkinsfile cleanup
* operator Dockerfile cleanup
* "flate.BestSpeed" as default archivation algorithm
=> [#122] Improve performance of model archiving

helms/odahu-flow-core/templates/api/server.yaml, helms/odahu-flow-core/templates/operator/connections.yaml
* Change policy for resource uploader job
=> [#112] Authorization

packages/cli/odahuflow/cli/main.py, packages/cli/odahuflow/cli/parsers/security.py, packages/cli/odahuflow/cli/version.py, packages/robot/odahuflow/robot/libraries/auth_client.py, packages/robot/odahuflow/robot/libraries/utils.py, packages/robot/odahuflow/robot/profiler_loader.py, packages/sdk/odahuflow/sdk/clients/api.py, packages/sdk/odahuflow/sdk/clients/oauth_handler.py, packages/sdk/odahuflow/sdk/clients/oidc.py, packages/sdk/odahuflow/sdk/config.py, packages/tests/e2e/robot/resources/keywords.robot, packages/tests/e2e/robot/tests/common/common_auth.robot, packages/tests/e2e/robot/tests/common/common_login.robot
* Add client_credentials flow login for SDK and CLI
* Add tests to login via client_credentials
* Change login to system on service account instead of direct access grant
https://github.com/odahu/odahu-flow/issues/131
=> [#131] SDK Client Credentials OAuth2

packages/robot/odahuflow/robot/profiler_loader.py
* Cluster FQDN calculation replaced by new profile variable
=> [cicd#68] DNS settings moved to profile

helms/odahu-flow-core/templates/operator/connections.yaml, helms/odahu-flow-core/values.yaml, packages/operator/cmd/packager/main.go, packages/operator/cmd/trainer/main.go, packages/operator/docs/docs.go, packages/operator/docs/swagger.json, packages/operator/docs/swagger.yaml, packages/operator/pkg/config/operator/operator.go, packages/operator/pkg/config/packager/packager.go, packages/operator/pkg/config/trainer/trainer.go, packages/operator/pkg/controller/modeldeployment/modeldeployment_controller.go, packages/operator/pkg/repository/connection/http/connection.go, packages/operator/pkg/repository/connection/http/connection_test.go, packages/operator/pkg/repository/packaging/http/model_packaging.go, packages/operator/pkg/repository/packaging/http/model_packaging_test.go, packages/operator/pkg/repository/packaging/http/packaging_integration_test.go, packages/operator/pkg/repository/training/http/model_training.go, packages/operator/pkg/repository/training/http/model_training_test.go, packages/operator/pkg/repository/training/http/toolchain_integration_test.go, packages/operator/pkg/repository/util/http/request.go, packages/robot/odahuflow/robot/profiler_loader.py, packages/sdk/odahuflow/sdk/clients/api.py
* odahu-flow-core chart accept sa credentials to upload connections to cluster
* profile_uploader in tests extract test sa credentials from new format profile var
* client can authorize via client_credentials flow now
=> [#113] Operator authentication

packages/operator/Makefile, packages/operator/pkg/repository/connection/vault/connection.go, packages/operator/pkg/validation/validation.go, packages/operator/pkg/validation/validation_test.go, packages/operator/pkg/webserver/routes/v1/connection/connection_validation.go, packages/operator/pkg/webserver/routes/v1/connection/connection_validation_test.go, packages/operator/pkg/webserver/routes/v1/deployment/model_deployment_validation.go, packages/operator/pkg/webserver/routes/v1/deployment/model_deployment_validation_test.go, packages/operator/pkg/webserver/routes/v1/deployment/modelroute_validation.go, packages/operator/pkg/webserver/routes/v1/deployment/modelroute_validation_test.go, packages/operator/pkg/webserver/routes/v1/packaging/model_packaging_validation.go, packages/operator/pkg/webserver/routes/v1/packaging/model_packaging_validation_test.go, packages/operator/pkg/webserver/routes/v1/packaging/packaging_integration_validation.go, packages/operator/pkg/webserver/routes/v1/packaging/packaging_intergration_validation_test.go, packages/operator/pkg/webserver/routes/v1/training/model_training_validation.go, packages/operator/pkg/webserver/routes/v1/training/model_training_validation_test.go, packages/operator/pkg/webserver/routes/v1/training/toolchain_integration_validation.go, packages/operator/pkg/webserver/routes/v1/training/toolchain_intergration_validation_test.go
This closes #147 
This closes #145
=> [feat] Improved validation ID and messages

.travis.yml, containers/operator/Dockerfile, packages/operator/docs/docs.go, packages/operator/docs/swagger.json, packages/operator/docs/swagger.yaml, packages/operator/pkg/controller/modelpackaging/modelpackaging_controller.go, packages/operator/pkg/controller/modelpackaging/modelpackaging_controller_test.go, packages/operator/pkg/controller/modelpackaging/tekton.go, packages/operator/pkg/controller/modeltraining/modeltraining_controller.go, packages/operator/pkg/controller/modeltraining/modeltraining_controller_test.go, packages/operator/pkg/controller/modeltraining/tekton.go, packages/operator/pkg/utils/tekton.go, packages/operator/pkg/utils/tekton_test.go, packages/operator/pkg/utils/zip.go, packages/operator/pkg/utils/zip_test.go, packages/tests/stuff/training_stuff.sh
* For now all helper containers have either limit main containers or default.
* Replaced zip with tar and pigz
This closes #122
=> [feat] Improvement performance of archiving

packages/robot/odahuflow/robot/profiler_loader.py
* New structure of cloud settings
=> [cicd#68] Cloud settings in profile

packages/cli/odahuflow/cli/parsers/config.py, packages/cli/odahuflow/cli/parsers/connection.py, packages/cli/odahuflow/cli/parsers/deployment.py, packages/cli/odahuflow/cli/parsers/local/packaging.py, packages/cli/odahuflow/cli/parsers/local/training.py, packages/cli/odahuflow/cli/parsers/packaging.py, packages/cli/odahuflow/cli/parsers/training.py, packages/sdk/odahuflow/sdk/local/packaging.py, packages/sdk/odahuflow/sdk/local/training.py
fix descriptions of commands and errors in odahuflowctl https://github.com/odahu/odahu-flow/issues/197
doesn't work of local training on Win 10 (change of join in PurePosixPath)
doesn't work local pack cleanup-containers https://github.com/odahu/odahu-flow/issues/204
=> update description to cli and fixes for local

packages/cli/odahuflow/cli/parsers/connection.py, packages/cli/odahuflow/cli/parsers/deployment.py, packages/cli/odahuflow/cli/parsers/model.py, packages/cli/odahuflow/cli/parsers/packaging.py, packages/cli/odahuflow/cli/parsers/packaging_integration.py, packages/cli/odahuflow/cli/parsers/route.py, packages/cli/odahuflow/cli/parsers/toolchain_integration.py, packages/cli/odahuflow/cli/parsers/training.py, packages/cli/odahuflow/cli/utils/output.py
* --output-format add options (yaml, json, table, jsonpath) https://github.com/odahu/odahu-flow/issues/209
Instead of click.Choice() just added to the help because it looks neater. 
* change [] in "Packaging not found" https://github.com/odahu/odahu-flow/issues/210
* updated variable names of route.py
tickets separated in commits.
=> updated output-format

Makefile, packages/cli/odahuflow/cli/parsers/bulk.py, packages/cli/odahuflow/cli/parsers/gppi.py, packages/cli/odahuflow/cli/parsers/packaging.py, packages/cli/odahuflow/cli/parsers/packaging_integration.py, packages/cli/odahuflow/cli/parsers/route.py, packages/operator/pkg/controller/deploymenthook/deploymenthook.go, packages/operator/pkg/controller/deploymenthook/deploymenthook_test.go, packages/operator/pkg/controller/modeltraining/tekton.go, packages/robot/odahuflow/robot/libraries/k8s.py, packages/sdk/odahuflow/sdk/gppi/executor.py
* GPPI Archive must be available to download even if validation step has been failed (e.g. for debug purposes)
=> #fix: order of tekton training steps

packages/cli/odahuflow/cli/parsers/connection.py, packages/cli/odahuflow/cli/parsers/packaging.py, packages/cli/odahuflow/cli/utils/error_handler.py, packages/cli/tests/parsers/test_actions_for_all_entities.py, packages/cli/tests/parsers/test_local.py, packages/sdk/odahuflow/sdk/gppi/executor.py
test for local (WinOS names folders case-insensitively) and error_handler.py.
=> corrected unittests

packages/tests/stuff/training_stuff.sh
=> [#75] Do not use fixed data bucket name

packages/operator/pkg/controller/modeldeployment/modeldeployment_controller_test.go
* We added new label for model deployment previously but not actualize tests
=> # Fix go test

packages/sdk/odahuflow/sdk/clients/api.py, packages/sdk/odahuflow/sdk/clients/packaging.py, packages/sdk/odahuflow/sdk/clients/training.py
* Now async API sdk client hasn't a blocking client as a wrong base class
=> #225 Fix inheritance for API clients

packages/tests/e2e/robot/tests/deployment/feedback.robot, packages/tests/e2e/robot/tests/deployment/routing.robot
updated deprecated version of FOR loop of robot framework
FOR END instead of :FOR  \.
=> updated deprecated FOR loop in robot framework

helms/odahu-flow-core/files/dashboards/api.json, helms/odahu-flow-core/files/dashboards/model-deployments.json, helms/odahu-flow-core/files/dashboards/operator.json
=> [#269] Metrics labels update

packages/operator/controllers/modeldeployment_controller.go, packages/operator/controllers/modeldeployment_controller_test.go, packages/operator/controllers/modelpackaging_controller.go, packages/operator/controllers/modelpackaging_controller_test.go, packages/operator/controllers/modeltraining_controller.go, packages/operator/controllers/modeltraining_controller_test.go, packages/operator/docs/docs.go, packages/operator/docs/swagger.json, packages/operator/docs/swagger.yaml, packages/operator/pkg/config/common.go, packages/operator/pkg/config/config.go, packages/operator/pkg/config/deployment.go, packages/operator/pkg/config/packaging.go, packages/operator/pkg/config/training.go, packages/sdk/odahuflow/sdk/models/external_url.py, packages/sdk/odahuflow/sdk/models/model_deployment_config.py, packages/sdk/odahuflow/sdk/models/model_packaging_config.py, packages/sdk/odahuflow/sdk/models/model_training_config.py, packages/tests/e2e/robot/tests/deployment/deploy_undeploy.robot
- Tolerations turned into arrays
- Several typos fixed
- Wierd resources units set to more human-readable manner
=> [cicd#178] Azure AKS Spot Node pools

Makefile, containers/robot-tests/Dockerfile, packages/tests/stuff/training_stuff.sh
- Verbosity turned off on rclone config creation step
- Rclone updated to v1.52.3
- Kubectl updated to v1.16.10
=> [feat] Hide secrets in `training_stuff.sh`

packages/robot/odahuflow/robot/cloud/object_storage.py, packages/robot/odahuflow/robot/libraries/utils.py, packages/robot/odahuflow/robot/profiler_loader.py, packages/robot/odahuflow/robot/training_data_helper.py, packages/sdk/odahuflow/sdk/clients/api.py, packages/sdk/odahuflow/sdk/clients/api_aggregated.py, packages/sdk/odahuflow/sdk/gppi/executor.py
Fix points from upgraded pylint about explicit refer to cause exception
=> Fix new rules from upgraded pylint (#268)

packages/operator/pkg/validation/validation.go, packages/operator/pkg/validation/validation_test.go
Fixes #294.
Fixed ID Validation regexp. 
Broken ID validation caused issues like #294.
=> [#294] Fixed ID validation

packages/operator/go.mod, packages/operator/pkg/apiserver/routes/v1/deployment/model_deployment_validation.go, packages/operator/pkg/apiserver/routes/v1/packaging/model_packaging_validation.go, packages/operator/pkg/apiserver/routes/v1/training/model_training_validation.go, packages/operator/pkg/rclone/azureblob.go, packages/operator/pkg/validation/validation.go, packages/operator/pkg/validation/validation_test.go
closes https://github.com/odahu/odahu-ui/issues/9
fix: can set requested resources bigger than limits and submit training [#9-odahu-ui]
=> Fix requests overflow limits

packages/cli/odahuflow/cli/parsers/connection.py, packages/cli/odahuflow/cli/parsers/deployment.py, packages/cli/odahuflow/cli/parsers/packaging.py, packages/cli/odahuflow/cli/parsers/packaging_integration.py, packages/cli/odahuflow/cli/parsers/route.py, packages/cli/odahuflow/cli/parsers/toolchain_integration.py, packages/cli/odahuflow/cli/parsers/training.py, packages/cli/odahuflow/cli/utils/error_handler.py, packages/cli/tests/parsers/test_actions_for_all_entities.py, packages/sdk/odahuflow/sdk/clients/packaging.py
Fixes #296 
This PR contains a few tiny fixes for CLI log messages.
=> [#296] Minor cli fixes

.pylintrc, packages/cli/odahuflow/cli/main.py, packages/cli/odahuflow/cli/parsers/completion.py, packages/cli/odahuflow/cli/parsers/security.py
- added PowerShell completion example
- updated docs of odahuflowctl cmd (similarly to kubectl)
- standardized logger in cli
=> powershell completion
